version: '3'

networks:
  my-network:
    driver: bridge

services:
  pgpool:
    container_name:
      pgpool
    image: bitnami/pgpool:4
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg0:5432,1:pg1:5432,2:pg2:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=postgres
      - PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT=yes
      - PGPOOL_ENABLE_LOG_CONNECTIONS=yes
      - PGPOOL_ENABLE_LOG_HOSTNAME=yes
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
  pg0:
    container_name:
      pg0
    image: postgres:14
    ports:
      - 5432
    volumes:
      - /Users/alibaba/Documents/GitHub/Distributed-Storage-Systems/lab4/pg0:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - pgpool
  pg1:
    container_name:
      pg1
    image: postgres:14
    ports:
      - 5432
    volumes:
      - /Users/alibaba/Documents/GitHub/Distributed-Storage-Systems/lab4/pg1:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - pg0
      - pgpool
  pg2:
    container_name:
      pg2
    image: postgres:14
    ports:
      - 5432
    volumes:
      - /Users/alibaba/Documents/GitHub/Distributed-Storage-Systems/lab4/pg2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - pg0
      - pgpool
